version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "om-random-coffee-bot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13uwrxe7mcsac"
s3_prefix = "om-random-coffee-bot"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
