AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  OM Random Coffee Bot

Parameters:
  TELEGRAM_API_KEY:
    Type: String
    Description: Telegram API Key
  MEMBERSHIP_CHAT_ID:
    Type: String
    Description: Chat to be in to use the bot

Globals:
  Function:
    Timeout: 1
    Runtime: python3.9
    Architectures:
      - x86_64

Resources:
  OMRandomCoffeeBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: bot.main
      Environment:
        Variables:
          TELEGRAM_API_KEY: !Ref TELEGRAM_API_KEY
          MEMBERSHIP_CHAT_ID: !Ref MEMBERSHIP_CHAT_ID
      FunctionUrlConfig:
        AuthType: NONE

Outputs:
  OMRandomCoffeeBotFunction:
    Description: "Lambda URL for OMRandomCoffeeBot function"
    Value:
      Fn::GetAtt: OMRandomCoffeeBotURL.FunctionUrl
